for i in {1..592}
do
    tar -xvf fake_test/${i}.tar.gz -C fake_test
done

tar -xvf real_train/324.tar.gz -C real_train
tar -xvf real_train/475.tar.gz -C real_train
tar -xvf real_train/575.tar.gz -C real_train
tar -xvf real_train/359.tar.gz -C real_train
tar -xvf real_train/259.tar.gz -C real_train
tar -xvf real_train/508.tar.gz -C real_train
tar -xvf real_train/516.tar.gz -C real_train
tar -xvf real_train/567.tar.gz -C real_train
tar -xvf real_train/236.tar.gz -C real_train
tar -xvf real_train/336.tar.gz -C real_train
tar -xvf real_train/181.tar.gz -C real_train
tar -xvf real_train/579.tar.gz -C real_train
tar -xvf real_train/228.tar.gz -C real_train
tar -xvf real_train/328.tar.gz -C real_train
tar -xvf real_train/2.tar.gz -C real_train
tar -xvf real_train/504.tar.gz -C real_train
tar -xvf real_train/255.tar.gz -C real_train
tar -xvf real_train/200.tar.gz -C real_train
tar -xvf real_train/551.tar.gz -C real_train
tar -xvf real_train/451.tar.gz -C real_train
tar -xvf real_train/263.tar.gz -C real_train
tar -xvf real_train/532.tar.gz -C real_train
tar -xvf real_train/363.tar.gz -C real_train
tar -xvf real_train/432.tar.gz -C real_train
tar -xvf real_train/312.tar.gz -C real_train
tar -xvf real_train/543.tar.gz -C real_train
tar -xvf real_train/212.tar.gz -C real_train
tar -xvf real_train/99.tar.gz -C real_train
tar -xvf real_train/420.tar.gz -C real_train
tar -xvf real_train/87.tar.gz -C real_train
tar -xvf real_train/520.tar.gz -C real_train
tar -xvf real_train/111.tar.gz -C real_train
tar -xvf real_train/494.tar.gz -C real_train
tar -xvf real_train/498.tar.gz -C real_train
tar -xvf real_train/21.tar.gz -C real_train
tar -xvf real_train/486.tar.gz -C real_train
tar -xvf real_train/160.tar.gz -C real_train
tar -xvf real_train/282.tar.gz -C real_train
tar -xvf real_train/382.tar.gz -C real_train
tar -xvf real_train/148.tar.gz -C real_train
tar -xvf real_train/17.tar.gz -C real_train
tar -xvf real_train/156.tar.gz -C real_train
tar -xvf real_train/127.tar.gz -C real_train
tar -xvf real_train/139.tar.gz -C real_train
tar -xvf real_train/144.tar.gz -C real_train
tar -xvf real_train/23.tar.gz -C real_train
tar -xvf real_train/484.tar.gz -C real_train
tar -xvf real_train/162.tar.gz -C real_train
tar -xvf real_train/101.tar.gz -C real_train
tar -xvf real_train/170.tar.gz -C real_train
tar -xvf real_train/496.tar.gz -C real_train
tar -xvf real_train/31.tar.gz -C real_train
tar -xvf real_train/113.tar.gz -C real_train
tar -xvf real_train/488.tar.gz -C real_train
tar -xvf real_train/588.tar.gz -C real_train
tar -xvf real_train/146.tar.gz -C real_train
tar -xvf real_train/125.tar.gz -C real_train
tar -xvf real_train/392.tar.gz -C real_train
tar -xvf real_train/64.tar.gz -C real_train
tar -xvf real_train/19.tar.gz -C real_train
tar -xvf real_train/68.tar.gz -C real_train
tar -xvf real_train/280.tar.gz -C real_train
tar -xvf real_train/76.tar.gz -C real_train
tar -xvf real_train/380.tar.gz -C real_train
tar -xvf real_train/406.tar.gz -C real_train
tar -xvf real_train/357.tar.gz -C real_train
tar -xvf real_train/565.tar.gz -C real_train
tar -xvf real_train/234.tar.gz -C real_train
tar -xvf real_train/465.tar.gz -C real_train
tar -xvf real_train/183.tar.gz -C real_train
tar -xvf real_train/338.tar.gz -C real_train
tar -xvf real_train/469.tar.gz -C real_train
tar -xvf real_train/569.tar.gz -C real_train
tar -xvf real_train/245.tar.gz -C real_train
tar -xvf real_train/326.tar.gz -C real_train
tar -xvf real_train/477.tar.gz -C real_train
tar -xvf real_train/226.tar.gz -C real_train
tar -xvf real_train/577.tar.gz -C real_train
tar -xvf real_train/422.tar.gz -C real_train
tar -xvf real_train/85.tar.gz -C real_train
tar -xvf real_train/522.tar.gz -C real_train
tar -xvf real_train/273.tar.gz -C real_train
tar -xvf real_train/441.tar.gz -C real_train
tar -xvf real_train/261.tar.gz -C real_train
tar -xvf real_train/530.tar.gz -C real_train
tar -xvf real_train/97.tar.gz -C real_train
tar -xvf real_train/430.tar.gz -C real_train
tar -xvf real_train/202.tar.gz -C real_train
tar -xvf real_train/453.tar.gz -C real_train
tar -xvf real_train/89.tar.gz -C real_train
tar -xvf real_train/11.tar.gz -C real_train
tar -xvf real_train/150.tar.gz -C real_train
tar -xvf real_train/284.tar.gz -C real_train
tar -xvf real_train/133.tar.gz -C real_train
tar -xvf real_train/388.tar.gz -C real_train
tar -xvf real_train/288.tar.gz -C real_train
tar -xvf real_train/121.tar.gz -C real_train
tar -xvf real_train/60.tar.gz -C real_train
tar -xvf real_train/296.tar.gz -C real_train
tar -xvf real_train/174.tar.gz -C real_train
tar -xvf real_train/492.tar.gz -C real_train
tar -xvf real_train/109.tar.gz -C real_train
tar -xvf real_train/48.tar.gz -C real_train
tar -xvf real_train/117.tar.gz -C real_train
tar -xvf real_train/56.tar.gz -C real_train
tar -xvf real_train/27.tar.gz -C real_train
tar -xvf real_train/166.tar.gz -C real_train
tar -xvf real_train/39.tar.gz -C real_train
tar -xvf real_train/44.tar.gz -C real_train
tar -xvf real_train/105.tar.gz -C real_train
tar -xvf real_train/265.tar.gz -C real_train
tar -xvf real_train/93.tar.gz -C real_train
tar -xvf real_train/549.tar.gz -C real_train
tar -xvf real_train/218.tar.gz -C real_train
tar -xvf real_train/318.tar.gz -C real_train
tar -xvf real_train/557.tar.gz -C real_train
tar -xvf real_train/457.tar.gz -C real_train
tar -xvf real_train/306.tar.gz -C real_train
tar -xvf real_train/377.tar.gz -C real_train
tar -xvf real_train/526.tar.gz -C real_train
tar -xvf real_train/369.tar.gz -C real_train
tar -xvf real_train/269.tar.gz -C real_train
tar -xvf real_train/538.tar.gz -C real_train
tar -xvf real_train/445.tar.gz -C real_train
tar -xvf real_train/214.tar.gz -C real_train
tar -xvf real_train/341.tar.gz -C real_train
tar -xvf real_train/510.tar.gz -C real_train
tar -xvf real_train/241.tar.gz -C real_train
tar -xvf real_train/195.tar.gz -C real_train
tar -xvf real_train/473.tar.gz -C real_train
tar -xvf real_train/322.tar.gz -C real_train
tar -xvf real_train/573.tar.gz -C real_train
tar -xvf real_train/222.tar.gz -C real_train
tar -xvf real_train/253.tar.gz -C real_train
tar -xvf real_train/502.tar.gz -C real_train
tar -xvf real_train/353.tar.gz -C real_train
tar -xvf real_train/402.tar.gz -C real_train
tar -xvf real_train/4.tar.gz -C real_train
tar -xvf real_train/199.tar.gz -C real_train
tar -xvf real_train/230.tar.gz -C real_train
tar -xvf real_train/561.tar.gz -C real_train
tar -xvf real_train/461.tar.gz -C real_train
tar -xvf real_train/316.tar.gz -C real_train
tar -xvf real_train/447.tar.gz -C real_train
tar -xvf real_train/216.tar.gz -C real_train
tar -xvf real_train/547.tar.gz -C real_train
tar -xvf real_train/83.tar.gz -C real_train
tar -xvf real_train/524.tar.gz -C real_train
tar -xvf real_train/308.tar.gz -C real_train
tar -xvf real_train/459.tar.gz -C real_train
tar -xvf real_train/208.tar.gz -C real_train
tar -xvf real_train/528.tar.gz -C real_train
tar -xvf real_train/279.tar.gz -C real_train
tar -xvf real_train/428.tar.gz -C real_train
tar -xvf real_train/379.tar.gz -C real_train
tar -xvf real_train/555.tar.gz -C real_train
tar -xvf real_train/204.tar.gz -C real_train
tar -xvf real_train/455.tar.gz -C real_train
tar -xvf real_train/91.tar.gz -C real_train
tar -xvf real_train/367.tar.gz -C real_train
tar -xvf real_train/232.tar.gz -C real_train
tar -xvf real_train/563.tar.gz -C real_train
tar -xvf real_train/251.tar.gz -C real_train
tar -xvf real_train/500.tar.gz -C real_train
tar -xvf real_train/6.tar.gz -C real_train
tar -xvf real_train/471.tar.gz -C real_train
tar -xvf real_train/320.tar.gz -C real_train
tar -xvf real_train/571.tar.gz -C real_train
tar -xvf real_train/220.tar.gz -C real_train
tar -xvf real_train/412.tar.gz -C real_train
tar -xvf real_train/343.tar.gz -C real_train
tar -xvf real_train/512.tar.gz -C real_train
tar -xvf real_train/243.tar.gz -C real_train
tar -xvf real_train/189.tar.gz -C real_train
tar -xvf real_train/123.tar.gz -C real_train
tar -xvf real_train/394.tar.gz -C real_train
tar -xvf real_train/62.tar.gz -C real_train
tar -xvf real_train/294.tar.gz -C real_train
tar -xvf real_train/140.tar.gz -C real_train
tar -xvf real_train/286.tar.gz -C real_train
tar -xvf real_train/70.tar.gz -C real_train
tar -xvf real_train/386.tar.gz -C real_train
tar -xvf real_train/13.tar.gz -C real_train
tar -xvf real_train/152.tar.gz -C real_train
tar -xvf real_train/298.tar.gz -C real_train
tar -xvf real_train/398.tar.gz -C real_train
tar -xvf real_train/46.tar.gz -C real_train
tar -xvf real_train/107.tar.gz -C real_train
tar -xvf real_train/582.tar.gz -C real_train
tar -xvf real_train/482.tar.gz -C real_train
tar -xvf real_train/58.tar.gz -C real_train
tar -xvf real_train/119.tar.gz -C real_train
tar -xvf real_train/29.tar.gz -C real_train
tar -xvf real_train/54.tar.gz -C real_train
tar -xvf real_train/176.tar.gz -C real_train
tar -xvf real_train/490.tar.gz -C real_train
tar -xvf real_train/37.tar.gz -C real_train
tar -xvf real_train/157.tar.gz -C real_train
tar -xvf real_train/16.tar.gz -C real_train
tar -xvf real_train/149.tar.gz -C real_train
tar -xvf real_train/283.tar.gz -C real_train
tar -xvf real_train/145.tar.gz -C real_train
tar -xvf real_train/138.tar.gz -C real_train
tar -xvf real_train/67.tar.gz -C real_train
tar -xvf real_train/291.tar.gz -C real_train
tar -xvf real_train/391.tar.gz -C real_train
tar -xvf real_train/32.tar.gz -C real_train
tar -xvf real_train/173.tar.gz -C real_train
tar -xvf real_train/495.tar.gz -C real_train
tar -xvf real_train/51.tar.gz -C real_train
tar -xvf real_train/110.tar.gz -C real_train
tar -xvf real_train/161.tar.gz -C real_train
tar -xvf real_train/20.tar.gz -C real_train
tar -xvf real_train/499.tar.gz -C real_train
tar -xvf real_train/102.tar.gz -C real_train
tar -xvf real_train/43.tar.gz -C real_train
tar -xvf real_train/433.tar.gz -C real_train
tar -xvf real_train/262.tar.gz -C real_train
tar -xvf real_train/533.tar.gz -C real_train
tar -xvf real_train/94.tar.gz -C real_train
tar -xvf real_train/86.tar.gz -C real_train
tar -xvf real_train/521.tar.gz -C real_train
tar -xvf real_train/270.tar.gz -C real_train
tar -xvf real_train/421.tar.gz -C real_train
tar -xvf real_train/98.tar.gz -C real_train
tar -xvf real_train/542.tar.gz -C real_train
tar -xvf real_train/213.tar.gz -C real_train
tar -xvf real_train/442.tar.gz -C real_train
tar -xvf real_train/346.tar.gz -C real_train
tar -xvf real_train/417.tar.gz -C real_train
tar -xvf real_train/225.tar.gz -C real_train
tar -xvf real_train/574.tar.gz -C real_train
tar -xvf real_train/474.tar.gz -C real_train
tar -xvf real_train/354.tar.gz -C real_train
tar -xvf real_train/505.tar.gz -C real_train
tar -xvf real_train/329.tar.gz -C real_train
tar -xvf real_train/229.tar.gz -C real_train
tar -xvf real_train/466.tar.gz -C real_train
tar -xvf real_train/180.tar.gz -C real_train
tar -xvf real_train/237.tar.gz -C real_train
tar -xvf real_train/440.tar.gz -C real_train
tar -xvf real_train/311.tar.gz -C real_train
tar -xvf real_train/84.tar.gz -C real_train
tar -xvf real_train/523.tar.gz -C real_train
tar -xvf real_train/272.tar.gz -C real_train
tar -xvf real_train/423.tar.gz -C real_train
tar -xvf real_train/372.tar.gz -C real_train
tar -xvf real_train/303.tar.gz -C real_train
tar -xvf real_train/452.tar.gz -C real_train
tar -xvf real_train/203.tar.gz -C real_train
tar -xvf real_train/552.tar.gz -C real_train
tar -xvf real_train/431.tar.gz -C real_train
tar -xvf real_train/260.tar.gz -C real_train
tar -xvf real_train/519.tar.gz -C real_train
tar -xvf real_train/335.tar.gz -C real_train
tar -xvf real_train/564.tar.gz -C real_train
tar -xvf real_train/407.tar.gz -C real_train
tar -xvf real_train/356.tar.gz -C real_train
tar -xvf real_train/256.tar.gz -C real_train
tar -xvf real_train/1.tar.gz -C real_train
tar -xvf real_train/227.tar.gz -C real_train
tar -xvf real_train/576.tar.gz -C real_train
tar -xvf real_train/190.tar.gz -C real_train
tar -xvf real_train/476.tar.gz -C real_train
tar -xvf real_train/515.tar.gz -C real_train
tar -xvf real_train/344.tar.gz -C real_train
tar -xvf real_train/239.tar.gz -C real_train
tar -xvf real_train/339.tar.gz -C real_train
tar -xvf real_train/18.tar.gz -C real_train
tar -xvf real_train/159.tar.gz -C real_train
tar -xvf real_train/65.tar.gz -C real_train
tar -xvf real_train/124.tar.gz -C real_train
tar -xvf real_train/147.tar.gz -C real_train
tar -xvf real_train/381.tar.gz -C real_train
tar -xvf real_train/136.tar.gz -C real_train
tar -xvf real_train/281.tar.gz -C real_train
tar -xvf real_train/77.tar.gz -C real_train
tar -xvf real_train/128.tar.gz -C real_train
tar -xvf real_train/585.tar.gz -C real_train
tar -xvf real_train/589.tar.gz -C real_train
tar -xvf real_train/53.tar.gz -C real_train
tar -xvf real_train/112.tar.gz -C real_train
tar -xvf real_train/30.tar.gz -C real_train
tar -xvf real_train/572.tar.gz -C real_train
tar -xvf real_train/223.tar.gz -C real_train
tar -xvf real_train/194.tar.gz -C real_train
tar -xvf real_train/472.tar.gz -C real_train
tar -xvf real_train/323.tar.gz -C real_train
tar -xvf real_train/511.tar.gz -C real_train
tar -xvf real_train/240.tar.gz -C real_train
tar -xvf real_train/340.tar.gz -C real_train
tar -xvf real_train/331.tar.gz -C real_train
tar -xvf real_train/460.tar.gz -C real_train
tar -xvf real_train/560.tar.gz -C real_train
tar -xvf real_train/198.tar.gz -C real_train
tar -xvf real_train/352.tar.gz -C real_train
tar -xvf real_train/403.tar.gz -C real_train
tar -xvf real_train/456.tar.gz -C real_train
tar -xvf real_train/556.tar.gz -C real_train
tar -xvf real_train/448.tar.gz -C real_train
tar -xvf real_train/219.tar.gz -C real_train
tar -xvf real_train/435.tar.gz -C real_train
tar -xvf real_train/364.tar.gz -C real_train
tar -xvf real_train/544.tar.gz -C real_train
tar -xvf real_train/539.tar.gz -C real_train
tar -xvf real_train/368.tar.gz -C real_train
tar -xvf real_train/439.tar.gz -C real_train
tar -xvf real_train/80.tar.gz -C real_train
tar -xvf real_train/276.tar.gz -C real_train
tar -xvf real_train/527.tar.gz -C real_train
tar -xvf real_train/427.tar.gz -C real_train
tar -xvf real_train/57.tar.gz -C real_train
tar -xvf real_train/108.tar.gz -C real_train
tar -xvf real_train/175.tar.gz -C real_train
tar -xvf real_train/493.tar.gz -C real_train
tar -xvf real_train/104.tar.gz -C real_train
tar -xvf real_train/38.tar.gz -C real_train
tar -xvf real_train/481.tar.gz -C real_train
tar -xvf real_train/167.tar.gz -C real_train
tar -xvf real_train/26.tar.gz -C real_train
tar -xvf real_train/385.tar.gz -C real_train
tar -xvf real_train/132.tar.gz -C real_train
tar -xvf real_train/297.tar.gz -C real_train
tar -xvf real_train/143.tar.gz -C real_train
tar -xvf real_train/59.tar.gz -C real_train
tar -xvf real_train/483.tar.gz -C real_train
tar -xvf real_train/165.tar.gz -C real_train
tar -xvf real_train/36.tar.gz -C real_train
tar -xvf real_train/491.tar.gz -C real_train
tar -xvf real_train/55.tar.gz -C real_train
tar -xvf real_train/114.tar.gz -C real_train
tar -xvf real_train/28.tar.gz -C real_train
tar -xvf real_train/63.tar.gz -C real_train
tar -xvf real_train/295.tar.gz -C real_train
tar -xvf real_train/122.tar.gz -C real_train
tar -xvf real_train/399.tar.gz -C real_train
tar -xvf real_train/299.tar.gz -C real_train
tar -xvf real_train/153.tar.gz -C real_train
tar -xvf real_train/12.tar.gz -C real_train
tar -xvf real_train/387.tar.gz -C real_train
tar -xvf real_train/130.tar.gz -C real_train
tar -xvf real_train/287.tar.gz -C real_train
tar -xvf real_train/71.tar.gz -C real_train
tar -xvf real_train/350.tar.gz -C real_train
tar -xvf real_train/250.tar.gz -C real_train
tar -xvf real_train/501.tar.gz -C real_train
tar -xvf real_train/333.tar.gz -C real_train
tar -xvf real_train/184.tar.gz -C real_train
tar -xvf real_train/188.tar.gz -C real_train
tar -xvf real_train/242.tar.gz -C real_train
tar -xvf real_train/413.tar.gz -C real_train
tar -xvf real_train/342.tar.gz -C real_train
tar -xvf real_train/570.tar.gz -C real_train
tar -xvf real_train/221.tar.gz -C real_train
tar -xvf real_train/196.tar.gz -C real_train
tar -xvf real_train/470.tar.gz -C real_train
tar -xvf real_train/321.tar.gz -C real_train
tar -xvf real_train/209.tar.gz -C real_train
tar -xvf real_train/558.tar.gz -C real_train
tar -xvf real_train/458.tar.gz -C real_train
tar -xvf real_train/374.tar.gz -C real_train
tar -xvf real_train/425.tar.gz -C real_train
tar -xvf real_train/546.tar.gz -C real_train
tar -xvf real_train/317.tar.gz -C real_train
tar -xvf real_train/437.tar.gz -C real_train
tar -xvf real_train/537.tar.gz -C real_train
tar -xvf real_train/90.tar.gz -C real_train
tar -xvf real_train/454.tar.gz -C real_train
tar -xvf real_train/429.tar.gz -C real_train
tar -xvf real_train/378.tar.gz -C real_train
tar -xvf real_train/529.tar.gz -C real_train

tar -xvf real_test/50.tar.gz -C real_test
tar -xvf real_test/74.tar.gz -C real_test
tar -xvf real_test/17.tar.gz -C real_test
tar -xvf real_test/66.tar.gz -C real_test
tar -xvf real_test/78.tar.gz -C real_test
tar -xvf real_test/.DS_Store -C real_test
tar -xvf real_test/52.tar.gz -C real_test
tar -xvf real_test/19.tar.gz -C real_test
tar -xvf real_test/15.tar.gz -C real_test
tar -xvf real_test/72.tar.gz -C real_test
tar -xvf real_test/27.tar.gz -C real_test
tar -xvf real_test/44.tar.gz -C real_test
tar -xvf real_test/93.tar.gz -C real_test
tar -xvf real_test/81.tar.gz -C real_test
tar -xvf real_test/8.tar.gz -C real_test
tar -xvf real_test/83.tar.gz -C real_test
tar -xvf real_test/91.tar.gz -C real_test
tar -xvf real_test/6.tar.gz -C real_test
tar -xvf real_test/13.tar.gz -C real_test
tar -xvf real_test/46.tar.gz -C real_test
tar -xvf real_test/29.tar.gz -C real_test
tar -xvf real_test/37.tar.gz -C real_test
tar -xvf real_test/16.tar.gz -C real_test
tar -xvf real_test/79.tar.gz -C real_test
tar -xvf real_test/32.tar.gz -C real_test
tar -xvf real_test/51.tar.gz -C real_test
tar -xvf real_test/86.tar.gz -C real_test
tar -xvf real_test/3.tar.gz -C real_test
tar -xvf real_test/84.tar.gz -C real_test
tar -xvf real_test/69.tar.gz -C real_test
tar -xvf real_test/41.tar.gz -C real_test
tar -xvf real_test/53.tar.gz -C real_test
tar -xvf real_test/9.tar.gz -C real_test
tar -xvf real_test/92.tar.gz -C real_test
tar -xvf real_test/57.tar.gz -C real_test
tar -xvf real_test/104.tar.gz -C real_test
tar -xvf real_test/45.tar.gz -C real_test
tar -xvf real_test/26.tar.gz -C real_test
tar -xvf real_test/73.tar.gz -C real_test
tar -xvf real_test/24.tar.gz -C real_test
tar -xvf real_test/28.tar.gz -C real_test
tar -xvf real_test/12.tar.gz -C real_test
tar -xvf real_test/82.tar.gz -C real_test
